version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      # Database connection string
      DB_CONNECTION_STRING: "postgres://root:root@postgres:5432/service?sslmode=disable"
      # Redis connection details
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    networks:
      - backend

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-service}
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge