name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build Docker image
      run: |
        docker build -t gcr.io/your-project-id/your-app .

    - name: Push Docker image
      run: |
        docker push gcr.io/your-project-id/your-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-app \
          --image gcr.io/your-project-id/your-app \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances your-instance-connection-name \
          --set-env-vars DB_CONNECTION_STRING="postgres://user:password@/dbname?host=/cloudsql/your-instance-connection-name&sslmode=disable"
